import dns from "node:dns/promises"; 
dns.setServers(["1.1.1.1", "8.8.8.8"]); 


import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth.api.getSession({
    headers: await headers()
  })

  const refresh = async(path) => {
    'use server';
    return revalidatePath(path);
  }


  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} h-full antialiased`}
    >
      <body className=" flex flex-col">
        <Navbar session={session} refresh={refresh}></Navbar>
        <main className="">{children}</main>
        <Footer></Footer>

        <ToastContainer />
      </body>
    </html>
  );
}
